# -- Theme Options --
# These options control how the theme functions and allow you to customize the display of your website.
# Refer to the theme docs for more details about each of these parameters.
# https://mnjm.github.io/kayal/docs/configuration/#theme-parameters

# [Optional] Path to the site logo image relative to assets/ folder. Displayed before the Site Title in the header. Minimum size: 64x64px.
logo = "/imgs/wd_logo.svg"
# Site description.
description = "I am a full-stack cloud application engineer and developer advocate passionate about distributed cloud applications. I am a golang enthusiast trapped in a Java dev's body. I have been a cloud-native aficionado since the moment I learned there was a world outside of VMs and server racks. My passions for event streaming and microservices fit nicely in the cloud. I love working for a global company, working with both technical and non-technical team members. I have served in a leadership role for the majority of my development career. In any role, I will contribute to the success of a software project by advocating internally and externally for all developers."
# [Optional] Copyright owner name.
copyright = ""
# Whether to optimize images per view port.
optimizeImg = true
# Whether to enable copy button in code blocks.
enableCodeCopy = true
# Show the icon that switches between dark and light themes when clicked.
showThemeSwitcher = true
# Default theme to start from. If "auto", it detects the previous preference/system theme.
defaultTheme = "auto"  # Valid Options: light, dark, auto
# When enabled, highlight the current menu item in the menu bar.
highlightCurrentMenu = true
# The sections to display in the recent articles list. If not provided, the section with the most articles is used.
mainSections = ["posts"]
# Whether to remove Hugo and theme attribution in the footer.
removeAttribution = false
# Whether to show anchor links in headings. Can be overridden by Page-specific `showHeadingAnchors` in its front matter.
showHeadingAnchors = true
# Whether to enable search. Needs JSON output for this to work.
enableSearch = true

# Site search engine verification tags.
# [verification]
# google = ""
# bing = ""
# pinterest = ""
# yandex = ""

# Homepage settings
[homepage]
# Whether to show recent items on the homepage.
showRecent = true
# Heading label for recent items.
showRecentLabel = "Recent Posts"
# Number of recent items to show.
showRecentItems = 50
# Whether to display a "Show more" link at the end of recent section that directs to `showMoreDest`.
showMore = true
showMoreDest = "/posts"
[homepage.profile]
# [Optional] Displayed at the top of your homepage.
# headline = "👋 Welcome to my site"
# [Optional] Path to the profile image relative to assets/ folder. Minimum size: 200x200px.
# image = "imgs/profile.svg"
# Image position.
where = "left"  # Options: right, left, top
image = "imgs/hs_sm.png"
# author = "AJ Danelz"
# headline = "DevRel 🥑"

# Article settings
[article]
# Whether to display article dates.
showDate = false
# Whether to display modified dates of articles.
showModDate = false
# Whether to display reading time of articles.
showReadingTime = false
# Whether to display tags mentioned in the front matter.
showTags = true
# Whether to display next/previous article links in the article footer.
showPagination = true
# Whether to reverse the direction of next/previous article links.
invertPagination = true
# Whether to display the table of contents on articles.
showToC = true
# Whether to open the Table of Contents when the page is loaded.
openToC = false
# Check https://mnjm.github.io/kayal/docs/advanced-customization/#comments
showComments = false
# Whether to display breadcrumbs
showBreadcrumbs = false

# List template settings
[list]
# Whether to group articles by year.
groupByYear = false
# Whether to display breadcrumbs
showBreadcrumbs = false
# Whether to display pages as a card
cardView = true
# Whether to display RSS link
showRSS = true

# Taxonomy settings
[taxonomy]
# Whether to show counts of each taxonomy term.
showCount = true
# Whether to display taxonomies as a grid of cards.
cardView = true

# Term settings
[term]
# Whether to group articles by year.
groupByYear = false
# Whether to display breadcrumbs
showBreadcrumbs = false
# Whether to display pages as a card
cardView = true
# Whether to display RSS link
showRSS = true

# Social links
[[social]]
icon = "github"
url = "https://github.com/vordimous"

[[social]]
icon = "gitlab"
url = "https://gitlab.com/vordimous"

[[social]]
icon = "linkedin"
url = "https://www.linkedin.com/in/andrew-danelz/"

[[social]]
icon = "x-twitter"
url = "https://x.com/vordimous"

[[social]]
icon = "bluesky"
url = "https://bsky.app/profile/vordimous.programmer.blue"

[[social]]
icon = "mastodon"
url = "https://mas.to/@vordimous"

[[social]]
icon = "link"
url = "https://linktr.ee/vordimous"


baseUrl = "https://wellaged.dev"
title = "WellAged.dev"
theme = "kayal"
enableRobotsTXT = true

[[menu.main]]
identifier = "about"
name = "About"
title = "About"
url = "/about/"
weight = 2
