languageCode: "en-us"
baseUrl: ""
title: "WellAged.dev"
theme: "anubis"
enableRobotsTXT: true

menu:
  main:
    - identifier: about
      name: About
      title: About
      url: /about
      weight: 1
    - identifier: notes
      name: Notes
      title: Notes
      url: /note/
      weight: 2

params:
  author: "AJ Danelz"
  email: mail@example.org # used for microformats
  avatar: "/images/me.png" # used for microformats
  description: "hi"
  # Uncomment if you need this
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/custom.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: false
  style: auto-without-switcher
  mainSections: ["post"] # which sections should be on index/main page
  sectionsWithFullContentOnListPage: ["note"] # for which sections content should be displayed on list pages
  readMore: false # show read more button
  disableSummary: false
  toc: true # display Table of Contents
  tocWordCount: 300 # ...when a post is longer than 300 words
  copyCodeButton: true # true by default
  rssAsSocialIcon: true
  # utteranc.es support
  utterancesRepo: "https://github.com/vordimous/wellageddev" # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  webmentions:
    url: https://yourdomain.com/webemntions/receive
    login: hugo-theme-anubis
    pingback: true
  social:
    - id: github
      name: vordimous

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
