baseUrl = "https://wellaged.dev"
title = "WellAged.dev"
theme = "kayal"
enableRobotsTXT = true

[[menu.main]]
identifier = "about"
name = "About"
title = "About"
url = "/about/"
weight = 2

[params]
navbar_logo = "/images/wd_logo.svg"
author = "AJ Danelz"
email = "mail@example.org"
avatar = "/images/wd_logo.svg"
description = "DevRel 🥑 @aklivity.io I am a full-stack engineer and developer advocate, passionate about cloud application design and Event-driven architecture."
images = [ "images/wd_logo.svg" ]
customCSS = [ "css/custom.css" ]
dateFormat = "2006-01-02"
paginationSinglePost = false
mainSections = [ "post" ]
readMore = false
disableSummary = false
toc = true
tocWordCount = 300
copyCodeButton = true
rssAsSocialIcon = true

[[params.social]]
id = "github"
url = "https://github.com/vordimous"

[[params.social]]
id = "gitlab"
url = "https://gitlab.com/vordimous"

[[params.social]]
id = "linkedin"
url = "https://www.linkedin.com/in/andrew-danelz/"

[[params.social]]
id = "x"
url = "https://x.com/vordimous"

[[params.social]]
id = "bluesky"
url = "https://bsky.app/profile/vordimous.bsky.social"

[[params.social]]
id = "mastodon"
url = "https://mas.to/@vordimous"

[[params.social]]
id = "email"
url = "https://linktr.ee/vordimous"

[markup.goldmark.renderer]
unsafe = true
